name: faculdade_app # Nome do seu aplicativo
description: App para gerenciar informações acadêmicas.
version: 1.0.0+1 # Versão do seu aplicativo
publish_to: 'none' # Define se o aplicativo será publicado

environment:
  sdk: '>=2.17.0 <3.0.0' # Define a versão do SDK Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  sqflite: ^2.0.0+2 # Banco de dados SQLite
  table_calendar: ^3.0.8
  go_router: ^6.0.0 # Roteamento
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.1.0
  flutter_local_notifications: ^17.2.2
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  # Adicione outras dependências conforme necessário...
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Linters para código
  shared_preferences: ^2.0.15 # Armazenamento de dados
  file_picker: ^5.2.2

flutter:
  uses-material-design: true # Define se o aplicativo usa o Material Design
  assets:
    - assets/imagens/coruja.png
    - assets/imagens/evento1.png
    - assets/imagens/evento2.png
    - assets/imagens/evento3.png
   
